# ############################
# ### AUTOSTART — MASTER ###
# ############################

# ----- System Services -----
exec-once = awww-daemon
exec-once = systemctl --user start hyprpolkitagent
exec-once = playerctld daemon
# Fallback: reative o portal residente do Explorer se o FileChooser custom falhar.
# exec-once = systemctl --user enable --now bench-filechooser-portal.service
# Monitor brightness and hardware controls
exec-once = bash $HOME/.local/share/Astrea/System/services/display_apply.sh
exec-once = quickshell -p ~/.local/share/Astrea/Features/Paper/app/lockscreen/Lockscreen.qml

# ----- Interface Components -----
exec-once = pkill -x playerctl || true
exec-once = quickshell -p ~/.config/quickshell
exec-once = hyprctl setcursor macOS 28
# ----- Wallpaper -----
exec-once = awww img $HOME/.local/share/Astrea/System/Lockscreen/Wallpaper/wallpaper.jpg

# ----- Theming (GTK) -----
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE HYPRLAND_INSTANCE_SIGNATURE XDG_RUNTIME_DIR PATH XDG_DATA_DIRS QT_QPA_PLATFORM QT_QPA_PLATFORMTHEME GTK_USE_PORTAL GTK_THEME
exec-once = systemctl --user import-environment WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE HYPRLAND_INSTANCE_SIGNATURE XDG_RUNTIME_DIR PATH XDG_DATA_DIRS QT_QPA_PLATFORM QT_QPA_PLATFORMTHEME GTK_USE_PORTAL GTK_THEME
exec-once = systemctl --user restart xdg-desktop-portal-hyprland xdg-desktop-portal
